export { angleFrom } from './functions/angleFrom'
export { bilerp } from './functions/bilerp'
export { cols } from './functions/cols'
export { degreesToRadians } from './functions/degreesToRadians'
export { flattenCols } from './functions/flattenCols'
export { flattenRows } from './functions/flattenRows'
export { flip } from './functions/flip'
export { hslToRgb } from './functions/hslToRgb'
export { intersect } from './functions/intersect'
export { isEven } from './functions/isEven'
export { lerp } from './functions/lerp'
export { lerpVectors } from './functions/lerpVectors'
export { measure } from './functions/measure'
export { parseColor } from './functions/parseColor'
export { polygon } from './functions/polygon'
export { radiansToDegrees } from './functions/radiansToDegrees'
export { rgbToHsl } from './functions/rgbToHsl'
export { rotateMatrix } from './functions/rotateMatrix'
export { rotateVector } from './functions/rotateVector'
export { rows } from './functions/rows'
export { slope } from './functions/slope'
export { stringifyColor } from './functions/stringifyColor'
export * from './types'

export const version = 'x.y.z'
