export { angleFrom } from './functions/angleFrom'
export { bilerp } from './functions/bilerp'
export { degreesToRadians } from './functions/degreesToRadians'
export { isEven } from './functions/isEven'
export { lerp } from './functions/lerp'
export { measure } from './functions/measure'
export { radiansToDegrees } from './functions/radiansToDegrees'
export * from './types'

export const version = 'x.y.z'
